<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit596dd8ab8ce0b978351375eb86796f06
{
    public static $prefixLengthsPsr4 = array (
        'W' => 
        array (
            'Woof\\ListTable\\' => 15,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Woof\\ListTable\\' => 
        array (
            0 => __DIR__ . '/../..' . '/class',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit596dd8ab8ce0b978351375eb86796f06::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit596dd8ab8ce0b978351375eb86796f06::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit596dd8ab8ce0b978351375eb86796f06::$classMap;

        }, null, ClassLoader::class);
    }
}
